//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : db
	/// Data Source    : db
	/// Server Version : 3.40.1
	/// </summary>
	public partial class DbDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Message> Messages { get { return this.GetTable<Message>(); } }
		public ITable<User>    Users    { get { return this.GetTable<User>(); } }

		#endregion

		#region .ctor

		public DbDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbDB(DataOptions<DbDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="Messages")]
	public partial class Message
	{
		[Column(),          PrimaryKey, Identity,    Nullable] public long?  ID            { get; set; } // INTEGER
		[Column(),          NotNull                          ] public long   From          { get; set; } // INTEGER
		[Column(),          NotNull                          ] public long   To            { get; set; } // INTEGER
		[Column("Message"),                          Nullable] public string MessageColumn { get; set; } // TEXT

		#region Associations

		/// <summary>
		/// FK_Messages_1 (main.User)
		/// </summary>
		[Association(ThisKey=nameof(From), OtherKey=nameof(DataModels.User.ID), CanBeNull=false)]
		public User FkMessages1 { get; set; }

		/// <summary>
		/// FK_Messages_0 (main.User)
		/// </summary>
		[Association(ThisKey=nameof(To), OtherKey=nameof(DataModels.User.ID), CanBeNull=false)]
		public User User { get; set; }

		#endregion
	}

	[Table(Schema="main", Name="User")]
	public partial class User
	{
		[Column,               Nullable] public string Name { get; set; } // TEXT
		[PrimaryKey, Identity, Nullable] public long?  ID   { get; set; } // INTEGER

		#region Associations

		/// <summary>
		/// FK_Messages_1_BackReference (main.Messages)
		/// </summary>
		[Association(ThisKey=nameof(ID), OtherKey=nameof(DataModels.Message.From), CanBeNull=true)]
		public IEnumerable<Message> FkMessages1BackReferences { get; set; }

		/// <summary>
		/// FK_Messages_0_BackReference (main.Messages)
		/// </summary>
		[Association(ThisKey=nameof(ID), OtherKey=nameof(DataModels.Message.To), CanBeNull=true)]
		public IEnumerable<Message> Messages { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Message Find(this ITable<Message> table, long? ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static User Find(this ITable<User> table, long? ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
