name: Create Release

on:
  push:
    tags:
      - "*-v[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter relevant files
        run: |
          rm -rf .github README.md .gitignore .git
      - name: Create a release archive
        run: |
          zip -r ${{ github.ref_name }}.zip .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: ${{ github.ref_name }}.zip