<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Dijkstra___Algorithmen</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="DACH.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="linq2db" Version="6.3.0" />
    <PackageReference Include="linq2db.SQLite" Version="6.3.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="DACH.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="model\cities.sqlite">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="model\natural-earth.sqlite">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="model\Cities.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Cities.generated.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="model\Cities.generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Cities.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
