//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : cities
	/// Data Source    : cities
	/// Server Version : 3.50.4
	/// </summary>
	public partial class CitiesDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Place> Places { get { return this.GetTable<Place>(); } }

		#endregion

		#region .ctor

		public CitiesDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public CitiesDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public CitiesDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public CitiesDB(DataOptions<CitiesDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="places")]
	public partial class Place
	{
		[Column("PK_UID"),    Nullable] public long?   PkUid     { get; set; } // INTEGER
		[Column("name"),      Nullable] public string  Name      { get; set; } // TEXT
		[Column("adm0name"),  Nullable] public string  Adm0name  { get; set; } // TEXT
		[Column("adm0_a3"),   Nullable] public string  Adm0A3    { get; set; } // TEXT
		[Column("adm1name"),  Nullable] public string  Adm1name  { get; set; } // TEXT
		[Column("latitude"),  Nullable] public double? Latitude  { get; set; } // REAL
		[Column("longitude"), Nullable] public double? Longitude { get; set; } // REAL
		[Column("pop_max"),   Nullable] public long?   PopMax    { get; set; } // INTEGER
		[Column("pop_min"),   Nullable] public long?   PopMin    { get; set; } // INTEGER
		[Column("timezone"),  Nullable] public string  Timezone  { get; set; } // TEXT
	}
}
