<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ressourcen\karte.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="linq2db" Version="6.3.0" />
    <PackageReference Include="linq2db.SQLite" Version="6.3.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ressourcen\karte.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="db\Model.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Model.generated.cs</LastGenOutput>
    </None>
    <None Update="db\Waldwunder.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="db\Model.generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Model.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
