// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class CUsersMarkusMatura2027Pos4WpfChatModelChatDbDb : DataConnection
	{
		public CUsersMarkusMatura2027Pos4WpfChatModelChatDbDb()
		{
			InitDataContext();
		}

		public CUsersMarkusMatura2027Pos4WpfChatModelChatDbDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public CUsersMarkusMatura2027Pos4WpfChatModelChatDbDb(DataOptions<CUsersMarkusMatura2027Pos4WpfChatModelChatDbDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}
}
