//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : chat
	/// Data Source    : chat
	/// Server Version : 3.40.1
	/// </summary>
	public partial class ChatDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Message>  Messages  { get { return this.GetTable<Message>(); } }
		public ITable<Room>     Rooms     { get { return this.GetTable<Room>(); } }
		public ITable<User>     Users     { get { return this.GetTable<User>(); } }
		public ITable<UserRoom> UserRooms { get { return this.GetTable<UserRoom>(); } }

		#endregion

		#region .ctor

		public ChatDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ChatDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ChatDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ChatDB(DataOptions<ChatDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="Message")]
	public partial class Message
	{
		[Column(),       PrimaryKey, Identity,    Nullable] public long?     MessageID { get; set; } // INTEGER
		[Column(),                                Nullable] public string    Text      { get; set; } // TEXT
		[Column("date"),                          Nullable] public DateTime? Date      { get; set; } // DATETIME
		[Column(),       NotNull                          ] public long      FromID    { get; set; } // INTEGER
		[Column(),       NotNull                          ] public long      ToID      { get; set; } // INTEGER

		#region Associations

		/// <summary>
		/// FK_Message_1 (main.User)
		/// </summary>
		[Association(ThisKey=nameof(FromID), OtherKey=nameof(DataModels.User.UserID), CanBeNull=false)]
		public User From { get; set; }

		/// <summary>
		/// FK_Message_0 (main.Room)
		/// </summary>
		[Association(ThisKey=nameof(ToID), OtherKey=nameof(DataModels.Room.RoomID), CanBeNull=false)]
		public Room To { get; set; }

		#endregion
	}

	[Table(Schema="main", Name="Room")]
	public partial class Room
	{
		[PrimaryKey, Identity,    Nullable] public long?  RoomID { get; set; } // INTEGER
		[Column,     NotNull              ] public string Name   { get; set; } // TEXT

		#region Associations

		/// <summary>
		/// FK_Message_0_BackReference (main.Message)
		/// </summary>
		[Association(ThisKey=nameof(RoomID), OtherKey=nameof(DataModels.Message.ToID), CanBeNull=true)]
		public IEnumerable<Message> Messages { get; set; }

		/// <summary>
		/// FK_User_Room_1_BackReference (main.User_Room)
		/// </summary>
		[Association(ThisKey=nameof(RoomID), OtherKey=nameof(DataModels.UserRoom.RoomID), CanBeNull=true)]
		public IEnumerable<UserRoom> Users { get; set; }

		#endregion
	}

	[Table(Schema="main", Name="User")]
	public partial class User
	{
		[PrimaryKey, Identity,    Nullable] public long?  UserID   { get; set; } // INTEGER
		[Column,     NotNull              ] public string Name     { get; set; } // TEXT
		[Column,     NotNull              ] public string Passwort { get; set; } // TEXT

		#region Associations

		/// <summary>
		/// FK_Message_1_BackReference (main.Message)
		/// </summary>
		[Association(ThisKey=nameof(UserID), OtherKey=nameof(DataModels.Message.FromID), CanBeNull=true)]
		public IEnumerable<Message> Messages { get; set; }

		/// <summary>
		/// FK_User_Room_0_BackReference (main.User_Room)
		/// </summary>
		[Association(ThisKey=nameof(UserID), OtherKey=nameof(DataModels.UserRoom.UserID), CanBeNull=true)]
		public IEnumerable<UserRoom> Rooms { get; set; }

		#endregion
	}

	[Table(Schema="main", Name="User_Room")]
	public partial class UserRoom
	{
		[PrimaryKey(0), Nullable] public long? UserID { get; set; } // INTEGER
		[PrimaryKey(1), Nullable] public long? RoomID { get; set; } // INTEGER

		#region Associations

		/// <summary>
		/// FK_User_Room_1 (main.Room)
		/// </summary>
		[Association(ThisKey=nameof(RoomID), OtherKey=nameof(DataModels.Room.RoomID), CanBeNull=true)]
		public Room Room { get; set; }

		/// <summary>
		/// FK_User_Room_0 (main.User)
		/// </summary>
		[Association(ThisKey=nameof(UserID), OtherKey=nameof(DataModels.User.UserID), CanBeNull=true)]
		public User User { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Message Find(this ITable<Message> table, long? MessageID)
		{
			return table.FirstOrDefault(t =>
				t.MessageID == MessageID);
		}

		public static Room Find(this ITable<Room> table, long? RoomID)
		{
			return table.FirstOrDefault(t =>
				t.RoomID == RoomID);
		}

		public static User Find(this ITable<User> table, long? UserID)
		{
			return table.FirstOrDefault(t =>
				t.UserID == UserID);
		}

		public static UserRoom Find(this ITable<UserRoom> table, long? UserID, long? RoomID)
		{
			return table.FirstOrDefault(t =>
				t.UserID == UserID &&
				t.RoomID == RoomID);
		}
	}
}
