<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Include="checkproj\checkproj.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RobotLibrary">
      <HintPath>..\..\..\RobotLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Aufgabe1.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Aufgabe2.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
