//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : worldcities
	/// Data Source    : worldcities
	/// Server Version : 3.50.4
	/// </summary>
	public partial class WorldcitiesDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Worldcity> Worldcities { get { return this.GetTable<Worldcity>(); } }

		#endregion

		#region .ctor

		public WorldcitiesDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public WorldcitiesDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public WorldcitiesDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public WorldcitiesDB(DataOptions<WorldcitiesDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="worldcities")]
	public partial class Worldcity
	{
		[Column("ogc_fid"),    PrimaryKey, Identity, Nullable] public long?   OgcFid     { get; set; } // INTEGER
		[Column(),                                   Nullable] public byte[]  GEOMETRY   { get; set; } // BLOB
		[Column("city"),                             Nullable] public string  City       { get; set; } // VARCHAR
		[Column("city_ascii"),                       Nullable] public string  CityAscii  { get; set; } // VARCHAR
		[Column("lat"),                              Nullable] public double? Lat        { get; set; } // FLOAT
		[Column("lng"),                              Nullable] public double? Lng        { get; set; } // FLOAT
		[Column("country"),                          Nullable] public string  Country    { get; set; } // VARCHAR
		[Column("iso2"),                             Nullable] public string  Iso2       { get; set; } // VARCHAR
		[Column("iso3"),                             Nullable] public string  Iso3       { get; set; } // VARCHAR
		[Column("admin_name"),                       Nullable] public string  AdminName  { get; set; } // VARCHAR
		[Column("capital"),                          Nullable] public string  Capital    { get; set; } // VARCHAR
		[Column("population"),                       Nullable] public long?   Population { get; set; } // INTEGER
		[Column("id"),                               Nullable] public string  Id         { get; set; } // VARCHAR
	}

	public static partial class TableExtensions
	{
		public static Worldcity Find(this ITable<Worldcity> table, long? OgcFid)
		{
			return table.FirstOrDefault(t =>
				t.OgcFid == OgcFid);
		}
	}
}
