//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : chat
	/// Data Source    : chat
	/// Server Version : 3.40.1
	/// </summary>
	public partial class ChatDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Message>  Messages  { get { return this.GetTable<Message>(); } }
		public ITable<Room>     Rooms     { get { return this.GetTable<Room>(); } }
		public ITable<RoomUser> RoomUsers { get { return this.GetTable<RoomUser>(); } }
		public ITable<User>     Users     { get { return this.GetTable<User>(); } }

		#endregion

		#region .ctor

		public ChatDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ChatDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ChatDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ChatDB(DataOptions<ChatDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="Message")]
	public partial class Message
	{
		[PrimaryKey, Identity,    Nullable] public long?  ID        { get; set; } // INTEGER
		[Column,     NotNull              ] public string Titel     { get; set; } // TEXT
		[Column,     NotNull              ] public string Content   { get; set; } // TEXT
		[Column,     NotNull              ] public long   Sender    { get; set; } // INTEGER
		[Column,                  Nullable] public long?  Receiver  { get; set; } // INTEGER
		[Column,                  Nullable] public long?  Room      { get; set; } // INTEGER
		[Column,     NotNull              ] public long   Timestamp { get; set; } // INTEGER

		#region Associations

		/// <summary>
		/// FK_Message_1 (main.Room)
		/// </summary>
		[Association(ThisKey=nameof(Room), OtherKey=nameof(DataModels.Room.ID), CanBeNull=true)]
		public Room Fk_Room { get; set; }

		/// <summary>
		/// FK_Message_2 (main.User)
		/// </summary>
		[Association(ThisKey=nameof(Receiver), OtherKey=nameof(DataModels.User.ID), CanBeNull=true)]
		public User Fk_Receiver { get; set; }

		/// <summary>
		/// FK_Message_0 (main.User)
		/// </summary>
		[Association(ThisKey=nameof(Sender), OtherKey=nameof(DataModels.User.ID), CanBeNull=false)]
		public User FK_Sender { get; set; }

		#endregion
	}

	[Table(Schema="main", Name="Room")]
	public partial class Room
	{
		[PrimaryKey, Identity,    Nullable] public long?  ID   { get; set; } // INTEGER
		[Column,     NotNull              ] public string Name { get; set; } // TEXT

		#region Associations

		/// <summary>
		/// FK_Message_1_BackReference (main.Message)
		/// </summary>
		[Association(ThisKey=nameof(ID), OtherKey=nameof(DataModels.Message.Room), CanBeNull=true)]
		public IEnumerable<Message> Messages { get; set; }

		/// <summary>
		/// FK_RoomUser_1_BackReference (main.RoomUser)
		/// </summary>
		[Association(ThisKey=nameof(ID), OtherKey=nameof(DataModels.RoomUser.Room), CanBeNull=true)]
		public IEnumerable<RoomUser> RoomUsers { get; set; }

		#endregion
	}

	[Table(Schema="main", Name="RoomUser")]
	public partial class RoomUser
	{
		[Column, Nullable] public long? Room { get; set; } // INTEGER
		[Column, Nullable] public long? User { get; set; } // INTEGER

		#region Associations

		/// <summary>
		/// FK_RoomUser_0 (main.User)
		/// </summary>
		[Association(ThisKey=nameof(User), OtherKey=nameof(DataModels.User.ID), CanBeNull=true)]
		public User Fk_User { get; set; }

		/// <summary>
		/// FK_RoomUser_1 (main.Room)
		/// </summary>
		[Association(ThisKey=nameof(Room), OtherKey=nameof(DataModels.Room.ID), CanBeNull=true)]
		public Room Fk_Room { get; set; }

		#endregion
	}

	[Table(Schema="main", Name="User")]
	public partial class User
	{
		[PrimaryKey, Identity,    Nullable] public long?  ID        { get; set; } // INTEGER
		[Column,     NotNull              ] public string Name      { get; set; } // TEXT
		[Column,     NotNull              ] public string Password  { get; set; } // TEXT
		[Column,                  Nullable] public long?  Timestamp { get; set; } // INTEGER

		#region Associations

		/// <summary>
		/// FK_Message_2_BackReference (main.Message)
		/// </summary>
		[Association(ThisKey=nameof(ID), OtherKey=nameof(DataModels.Message.Receiver), CanBeNull=true)]
		public IEnumerable<Message> Fk_ReceivedMessages { get; set; }

		/// <summary>
		/// FK_Message_0_BackReference (main.Message)
		/// </summary>
		[Association(ThisKey=nameof(ID), OtherKey=nameof(DataModels.Message.Sender), CanBeNull=true)]
		public IEnumerable<Message> Fk_SentMessages { get; set; }

		/// <summary>
		/// FK_RoomUser_0_BackReference (main.RoomUser)
		/// </summary>
		[Association(ThisKey=nameof(ID), OtherKey=nameof(DataModels.RoomUser.User), CanBeNull=true)]
		public IEnumerable<RoomUser> RoomUsers { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Message Find(this ITable<Message> table, long? ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Room Find(this ITable<Room> table, long? ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static User Find(this ITable<User> table, long? ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
