<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WPF_Chat_Server</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="linq2db" Version="6.1.0" />
    <PackageReference Include="linq2db.SQLite" Version="6.1.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NetworkLibrary">
      <HintPath>..\..\Server\NetworkLibrary\bin\Debug\net8.0\NetworkLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="chat.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Model\chat.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="VSModel\chat.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="VSModel\ChatDatabase.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ChatDatabase.generated.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="VSModel\ChatDatabase.generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ChatDatabase.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
