//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : chat
	/// Data Source    : chat
	/// Server Version : 3.40.1
	/// </summary>
	public partial class ChatDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<User> Users { get { return this.GetTable<User>(); } }

		#endregion

		#region .ctor

		public ChatDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ChatDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ChatDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ChatDB(DataOptions<ChatDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="User")]
	public partial class User
	{
		[PrimaryKey, Identity] public long   ID       { get; set; } // INTEGER
		[Column,     NotNull ] public string Username { get; set; } // TEXT
		[Column,     NotNull ] public string Password { get; set; } // TEXT
	}

	public static partial class TableExtensions
	{
		public static User Find(this ITable<User> table, long ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}

