<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wordl.generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>wordl.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="linq2db" Version="6.2.1" />
    <PackageReference Include="linq2db.SQLite" Version="6.2.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Network\Network.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wordl.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="wordl.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>wordl.generated.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
