//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : wordl
	/// Data Source    : wordl
	/// Server Version : 3.40.1
	/// </summary>
	public partial class WordlDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Word> Words { get { return this.GetTable<Word>(); } }

		#endregion

		#region .ctor

		public WordlDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public WordlDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public WordlDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public WordlDB(DataOptions<WordlDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="Words")]
	public partial class Word
	{
		[Column(),       PrimaryKey, Identity,    Nullable] public long?  Id         { get; set; } // INTEGER
		[Column("Word"), NotNull                          ] public string WordColumn { get; set; } // TEXT
		[Column(),                                Nullable] public long?  Try1       { get; set; } // INTEGER
		[Column(),                                Nullable] public long?  Try2       { get; set; } // INTEGER
		[Column(),                                Nullable] public long?  Try3       { get; set; } // INTEGER
		[Column(),                                Nullable] public long?  Try4       { get; set; } // INTEGER
		[Column(),                                Nullable] public long?  Try5       { get; set; } // INTEGER
		[Column(),                                Nullable] public long?  Try6       { get; set; } // INTEGER
		[Column(),                                Nullable] public long?  Failed     { get; set; } // INTEGER
	}

	public static partial class TableExtensions
	{
		public static Word Find(this ITable<Word> table, long? Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
