//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Formen
	/// Data Source    : Formen
	/// Server Version : 3.50.4
	/// </summary>
	public partial class FormenDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Forman> Formen { get { return this.GetTable<Forman>(); } }
		public ITable<Line>   Lines  { get { return this.GetTable<Line>(); } }

		#endregion

		#region .ctor

		public FormenDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public FormenDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public FormenDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public FormenDB(DataOptions<FormenDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="Formen")]
	public partial class Forman
	{
		[PrimaryKey, Identity, Nullable] public long?  ID   { get; set; } // INTEGER
		[Column,               Nullable] public string Name { get; set; } // TEXT

		#region Associations

		/// <summary>
		/// FK_Lines_0_BackReference (main.Lines)
		/// </summary>
		[Association(ThisKey=nameof(ID), OtherKey=nameof(DataModels.Line.Form), CanBeNull=true)]
		public IEnumerable<Line> Lines { get; set; }

        public override string ToString() {
			return Name;
        }

		#endregion
	}

	[Table(Schema="main", Name="Lines")]
	public partial class Line
	{
		[PrimaryKey, Identity, Nullable] public long? ID   { get; set; } // INTEGER
		[Column,               Nullable] public long? X    { get; set; } // INTEGER
		[Column,               Nullable] public long? Y    { get; set; } // INTEGER
		[Column,               Nullable] public long? Form { get; set; } // INTEGER

		#region Associations

		/// <summary>
		/// FK_Lines_0 (main.Formen)
		/// </summary>
		[Association(ThisKey=nameof(Form), OtherKey=nameof(DataModels.Forman.ID), CanBeNull=true)]
		public Forman Forman { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Forman Find(this ITable<Forman> table, long? ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Line Find(this ITable<Line> table, long? ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
