// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("User")]
	public class User
	{
		[Column("ID"      , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long?  Id       { get; set; } // INTEGER
		[Column("Name"    , CanBeNull    = false                                                             )] public string Name     { get; set; } = null!; // TEXT
		[Column("Password", CanBeNull    = false                                                             )] public string Password { get; set; } = null!; // TEXT
	}
}
